package dev.zekez.plushies;

import eu.pb4.polymer.core.api.item.PolymerItemGroupUtils;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.entity.EquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.item.SnowballItem;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import net.minecraft.util.Rarity;

import java.util.ArrayList;
import java.util.List;

import static dev.zekez.plushies.PolyPlushies.MOD_ID;

public class Blocks {
    public static final Identifier SNOW_GOLEM_BLOCK_ID = Identifier.of(MOD_ID, "snow_golem_plushie");
    public static final Identifier AXOLOTL_BLOCK_ID = Identifier.of(MOD_ID, "axolotl_plushie");
    public static final Identifier BEE_BLOCK_ID = Identifier.of(MOD_ID, "bee_plushie");
    public static final Identifier CAT_BLOCK_ID = Identifier.of(MOD_ID, "cat_plushie");
    public static final Identifier COW_BLOCK_ID = Identifier.of(MOD_ID, "cow_plushie");
    public static final Identifier DOLPHIN_BLOCK_ID = Identifier.of(MOD_ID, "dolphin_plushie");
    public static final Identifier DRAGON_BLOCK_ID = Identifier.of(MOD_ID, "dragon_plushie");
    public static final Identifier ENDERMAN_BLOCK_ID = Identifier.of(MOD_ID, "enderman_plushie");
    public static final Identifier FROG_BLOCK_ID = Identifier.of(MOD_ID, "frog_plushie");
    public static final Identifier GOAT_BLOCK_ID = Identifier.of(MOD_ID, "goat_plushie");
    public static final Identifier LLAMA_BLOCK_ID = Identifier.of(MOD_ID, "llama_plushie");
    public static final Identifier SLIME_BLOCK_ID = Identifier.of(MOD_ID, "slime_plushie");
    public static final Identifier MAGMA_CUBE_BLOCK_ID = Identifier.of(MOD_ID, "magma_cube_plushie");
    public static final Identifier MOOSHROOM_BLOCK_ID = Identifier.of(MOD_ID, "mooshroom_plushie");
    public static final Identifier PANDA_BLOCK_ID = Identifier.of(MOD_ID, "panda_plushie");
    public static final Identifier PARROT_BLOCK_ID = Identifier.of(MOD_ID, "parrot_plushie");
    public static final Identifier RED_FOX_BLOCK_ID = Identifier.of(MOD_ID, "red_fox_plushie");
    public static final Identifier WHITE_FOX_BLOCK_ID = Identifier.of(MOD_ID, "white_fox_plushie");
    public static final Identifier WARDEN_BLOCK_ID = Identifier.of(MOD_ID, "warden_plushie");
    public static final Identifier SHEEP_BLOCK_ID = Identifier.of(MOD_ID, "sheep_plushie");
    public static final Identifier TURTLE_BLOCK_ID = Identifier.of(MOD_ID, "turtle_plushie");
    public static final Identifier ALLAY_BLOCK_ID = Identifier.of(MOD_ID, "allay_plushie");
    public static final Identifier TADPOLE_BLOCK_ID = Identifier.of(MOD_ID, "tadpole_plushie");
    public static final Identifier PIG_BLOCK_ID = Identifier.of(MOD_ID, "pig_plushie");
    public static final Identifier VEX_BLOCK_ID = Identifier.of(MOD_ID, "vex_plushie");
    public static final Identifier BROWN_RABBIT_BLOCK_ID = Identifier.of(MOD_ID, "brown_rabbit_plushie");
    public static final Identifier WHITE_RABBIT_BLOCK_ID = Identifier.of(MOD_ID, "white_rabbit_plushie");
    public static final Identifier BLACK_RABBIT_BLOCK_ID = Identifier.of(MOD_ID, "black_rabbit_plushie");
    public static final Identifier WHITE_SPLOTCHED_RABBIT_BLOCK_ID = Identifier.of(MOD_ID, "white_splotched_rabbit_plushie");
    public static final Identifier YELLOW_RABBIT_BLOCK_ID = Identifier.of(MOD_ID, "yellow_rabbit_plushie");
    public static final Identifier SALT_RABBIT_BLOCK_ID = Identifier.of(MOD_ID, "salt_rabbit_plushie");
    public static final Identifier KILLER_RABBIT_BLOCK_ID = Identifier.of(MOD_ID, "killer_bunny_plushie");
    public static final Identifier TOAST_RABBIT_BLOCK_ID = Identifier.of(MOD_ID, "toast_rabbit_plushie");
    public static final Identifier STRIDER_BLOCK_ID = Identifier.of(MOD_ID, "strider_plushie");
    public static final Identifier ENDERMITE_BLOCK_ID = Identifier.of(MOD_ID, "endermite_plushie");
    public static final Identifier CHICKEN_BLOCK_ID = Identifier.of(MOD_ID, "chicken_plushie");
    public static final Identifier EVOKER_BLOCK_ID = Identifier.of(MOD_ID, "evoker_plushie");
    public static final Identifier VINDICATOR_BLOCK_ID = Identifier.of(MOD_ID, "vindicator_plushie");
    public static final Identifier ZOMBIE_BLOCK_ID = Identifier.of(MOD_ID, "zombie_plushie");
    public static final Identifier WOLF_BLOCK_ID = Identifier.of(MOD_ID, "wolf_plushie");
    public static final Identifier SQUID_BLOCK_ID = Identifier.of(MOD_ID, "squid_plushie");
    public static final Identifier GLOW_SQUID_BLOCK_ID = Identifier.of(MOD_ID, "glow_squid_plushie");
    public static final Identifier PILLAGER_BLOCK_ID = Identifier.of(MOD_ID, "pillager_plushie");
    public static final Identifier ILLUSIONER_BLOCK_ID = Identifier.of(MOD_ID, "illusioner_plushie");
    public static final Identifier CAMEL_BLOCK_ID = Identifier.of(MOD_ID, "camel_plushie");
    public static final Identifier GUARDIAN_BLOCK_ID = Identifier.of(MOD_ID, "guardian_plushie");
    public static final Identifier ELDER_GUARDIAN_BLOCK_ID = Identifier.of(MOD_ID, "elder_guardian_plushie");
    public static final Identifier SNIFFER_BLOCK_ID = Identifier.of(MOD_ID, "sniffer_plushie");
    public static final Identifier POLAR_BEAR_BLOCK_ID = Identifier.of(MOD_ID, "polar_bear_plushie");
    public static final Identifier WITCH_BLOCK_ID = Identifier.of(MOD_ID, "witch_plushie");
    public static final Identifier RAVAGER_BLOCK_ID = Identifier.of(MOD_ID, "ravager_plushie");
    public static final Identifier HORSE_BLOCK_ID = Identifier.of(MOD_ID, "horse_plushie");
    public static final Identifier SPIDER_BLOCK_ID = Identifier.of(MOD_ID, "spider_plushie");
    public static final Identifier CREEPER_BLOCK_ID = Identifier.of(MOD_ID, "creeper_plushie");
    public static final Identifier HUSK_BLOCK_ID = Identifier.of(MOD_ID, "husk_plushie");
    public static final Identifier WARM_FROG_BLOCK_ID = Identifier.of(MOD_ID, "warm_frog_plushie");
    public static final Identifier COLD_FROG_BLOCK_ID = Identifier.of(MOD_ID, "cold_frog_plushie");
    public static final Identifier PUFFERFISH_BLOCK_ID = Identifier.of(MOD_ID, "pufferfish_plushie");
    public static final Identifier HOGLIN_BLOCK_ID = Identifier.of(MOD_ID, "hoglin_plushie");
    public static final Identifier OCELOT_BLOCK_ID = Identifier.of(MOD_ID, "ocelot_plushie");
    public static final Identifier BAT_BLOCK_ID = Identifier.of(MOD_ID, "bat_plushie");
    public static final Identifier SALMON_BLOCK_ID = Identifier.of(MOD_ID, "salmon_plushie");
    public static final Identifier ZOGLIN_BLOCK_ID = Identifier.of(MOD_ID, "zoglin_plushie");
    public static final Identifier COD_BLOCK_ID = Identifier.of(MOD_ID, "cod_plushie");
    public static final Identifier PIGLIN_BLOCK_ID = Identifier.of(MOD_ID, "piglin_plushie");
    public static final Identifier BRUTE_BLOCK_ID = Identifier.of(MOD_ID, "piglin_brute_plushie");
    public static final Identifier ZOMPIGLIN_BLOCK_ID = Identifier.of(MOD_ID, "zombiefied_piglin_plushie");
    public static final Identifier VILLAGER_BLOCK_ID = Identifier.of(MOD_ID, "villager_plushie");
    public static final Identifier WANDERING_TRADER_BLOCK_ID = Identifier.of(MOD_ID, "wandering_trader_plushie");
    public static final Identifier DROWNED_BLOCK_ID = Identifier.of(MOD_ID, "drowned_plushie");
    public static final Identifier SHULKER_BLOCK_ID = Identifier.of(MOD_ID, "shulker_plushie");
    public static final Identifier ZOMBIE_VILLAGER_BLOCK_ID = Identifier.of(MOD_ID, "zombie_villager_plushie");
    public static final Identifier GOLEM_BLOCK_ID = Identifier.of(MOD_ID, "iron_golem_plushie");
    public static final Identifier SKELETON_BLOCK_ID = Identifier.of(MOD_ID, "skeleton_plushie");
    public static final Identifier WITHER_SKELETON_BLOCK_ID = Identifier.of(MOD_ID, "wither_skeleton_plushie");
    public static final Identifier CAVE_SPIDER_BLOCK_ID = Identifier.of(MOD_ID, "cave_spider_plushie");
    public static final Identifier SKELETON_HORSE_BLOCK_ID = Identifier.of(MOD_ID, "skeleton_horse_plushie");
    public static final Identifier STRAY_BLOCK_ID = Identifier.of(MOD_ID, "stray_plushie");
    public static final Identifier SILVERFISH_BLOCK_ID = Identifier.of(MOD_ID, "silverfish_plushie");
    public static final Identifier BLAZE_BLOCK_ID = Identifier.of(MOD_ID, "blaze_plushie");
    public static final Identifier GHAST_BLOCK_ID = Identifier.of(MOD_ID, "ghast_plushie");
    public static final Identifier WITHER_BLOCK_ID = Identifier.of(MOD_ID, "wither_plushie");
    public static final Identifier PHANTOM_BLOCK_ID = Identifier.of(MOD_ID, "phantom_plushie");
    public static final Identifier SMALL_TROP_BLOCK_ID = Identifier.of(MOD_ID, "small_tropical_fish_plushie");
    public static final Identifier LARGE_TROP_BLOCK_ID = Identifier.of(MOD_ID, "large_tropical_fish_plushie");
    public static final Identifier ARMADILLO_BLOCK_ID = Identifier.of(MOD_ID, "armadillo_plushie");
    public static final Identifier BREEZE_BLOCK_ID = Identifier.of(MOD_ID, "breeze_plushie");
    public static final Identifier ZOMBIE_HORSE_BLOCK_ID = Identifier.of(MOD_ID, "zombie_horse_plushie");
    public static final Identifier BOGGED_BLOCK_ID = Identifier.of(MOD_ID, "bogged_plushie");
    public static final Identifier MULE_BLOCK_ID = Identifier.of(MOD_ID, "mule_plushie");
    public static final Identifier DONKEY_BLOCK_ID = Identifier.of(MOD_ID, "donkey_plushie");

    public static Block SNOW_GOLEM_BLOCK;
    public static Block AXOLOTL_BLOCK;
    public static Block BEE_BLOCK;
    public static Block CAT_BLOCK;
    public static Block COW_BLOCK;
    public static Block DOLPHIN_BLOCK;
    public static Block DRAGON_BLOCK;
    public static Block ENDERMAN_BLOCK;
    public static Block FROG_BLOCK;
    public static Block GOAT_BLOCK;
    public static Block LLAMA_BLOCK;
    public static Block SLIME_BLOCK;
    public static Block MAGMA_CUBE_BLOCK;
    public static Block MOOSHROOM_BLOCK;
    public static Block PANDA_BLOCK;
    public static Block PARROT_BLOCK;
    public static Block RED_FOX_BLOCK;
    public static Block WHITE_FOX_BLOCK;
    public static Block WARDEN_BLOCK;
    public static Block SHEEP_BLOCK;
    public static Block TURTLE_BLOCK;
    public static Block ALLAY_BLOCK;
    public static Block TADPOLE_BLOCK;
    public static Block PIG_BLOCK;
    public static Block VEX_BLOCK;
    public static Block BROWN_RABBIT_BLOCK;
    public static Block WHITE_RABBIT_BLOCK;
    public static Block BLACK_RABBIT_BLOCK;
    public static Block WHITE_SPLOTCHED_RABBIT_BLOCK;
    public static Block YELLOW_RABBIT_BLOCK;
    public static Block SALT_RABBIT_BLOCK;
    public static Block KILLER_RABBIT_BLOCK;
    public static Block TOAST_RABBIT_BLOCK;
    public static Block STRIDER_BLOCK;
    public static Block ENDERMITE_BLOCK;
    public static Block CHICKEN_BLOCK;
    public static Block EVOKER_BLOCK;
    public static Block VINDICATOR_BLOCK;
    public static Block ZOMBIE_BLOCK;
    public static Block WOLF_BLOCK;
    public static Block SQUID_BLOCK;
    public static Block GLOW_SQUID_BLOCK;
    public static Block PILLAGER_BLOCK;
    public static Block ILLUSIONER_BLOCK;
    public static Block CAMEL_BLOCK;
    public static Block GUARDIAN_BLOCK;
    public static Block ELDER_GUARDIAN_BLOCK;
    public static Block SNIFFER_BLOCK;
    public static Block POLAR_BEAR_BLOCK;
    public static Block WITCH_BLOCK;
    public static Block RAVAGER_BLOCK;
    public static Block HORSE_BLOCK;
    public static Block SPIDER_BLOCK;
    public static Block CREEPER_BLOCK;
    public static Block HUSK_BLOCK;
    public static Block WARM_FROG_BLOCK;
    public static Block COLD_FROG_BLOCK;
    public static Block PUFFERFISH_BLOCK;
    public static Block HOGLIN_BLOCK;
    public static Block OCELOT_BLOCK;
    public static Block BAT_BLOCK;
    public static Block SALMON_BLOCK;
    public static Block ZOGLIN_BLOCK;
    public static Block COD_BLOCK;
    public static Block PIGLIN_BLOCK;
    public static Block BRUTE_BLOCK;
    public static Block ZOMPIGLIN_BLOCK;
    public static Block VILLAGER_BLOCK;
    public static Block WANDERING_TRADER_BLOCK;
    public static Block DROWNED_BLOCK;
    public static Block SHULKER_BLOCK;
    public static Block ZOMBIE_VILLAGER_BLOCK;
    public static Block GOLEM_BLOCK;
    public static Block SKELETON_BLOCK;
    public static Block WITHER_SKELETON_BLOCK;
    public static Block CAVE_SPIDER_BLOCK;
    public static Block SKELETON_HORSE_BLOCK;
    public static Block STRAY_BLOCK;
    public static Block SILVERFISH_BLOCK;
    public static Block BLAZE_BLOCK;
    public static Block GHAST_BLOCK;
    public static Block WITHER_BLOCK;
    public static Block PHANTOM_BLOCK;
    public static Block SMALL_TROP_BLOCK;
    public static Block LARGE_TROP_BLOCK;
    public static Block ARMADILLO_BLOCK;
    public static Block BREEZE_BLOCK;
    public static Block ZOMBIE_HORSE_BLOCK;
    public static Block BOGGED_BLOCK;
    public static Block MULE_BLOCK;
    public static Block DONKEY_BLOCK;

    public static List<Block> BLOCKS = new ArrayList<>();
    public static List<Item> ITEMS = new ArrayList<>();

    public static final ItemGroup ITEM_GROUP = PolymerItemGroupUtils.builder()
            .displayName(Text.of("Poly Plushies"))
            .icon(() -> new ItemStack(SNOW_GOLEM_BLOCK)).entries((context, entries) -> {
                for (Item item : ITEMS) {
                    entries.add(new ItemStack(item));
                }
            }).build();

    public static void register() {
        SNOW_GOLEM_BLOCK = registerPlushieBlockAndItem(SNOW_GOLEM_BLOCK_ID);
        AXOLOTL_BLOCK = registerPlushieBlockAndItem(AXOLOTL_BLOCK_ID);
        BEE_BLOCK = registerPlushieBlockAndItem(BEE_BLOCK_ID);
        CAT_BLOCK = registerPlushieBlockAndItem(CAT_BLOCK_ID);
        COW_BLOCK = registerPlushieBlockAndItem(COW_BLOCK_ID);
        DOLPHIN_BLOCK = registerPlushieBlockAndItem(DOLPHIN_BLOCK_ID);
        DRAGON_BLOCK = registerPlushieBlockAndItem(DRAGON_BLOCK_ID, Rarity.EPIC);
        ENDERMAN_BLOCK = registerPlushieBlockAndItem(ENDERMAN_BLOCK_ID);
        FROG_BLOCK = registerPlushieBlockAndItem(FROG_BLOCK_ID);
        GOAT_BLOCK = registerPlushieBlockAndItem(GOAT_BLOCK_ID);
        LLAMA_BLOCK = registerPlushieBlockAndItem(LLAMA_BLOCK_ID);
        SLIME_BLOCK = registerPlushieBlockAndItem(SLIME_BLOCK_ID);
        MAGMA_CUBE_BLOCK = registerPlushieBlockAndItem(MAGMA_CUBE_BLOCK_ID);
        MOOSHROOM_BLOCK = registerPlushieBlockAndItem(MOOSHROOM_BLOCK_ID);
        PANDA_BLOCK = registerPlushieBlockAndItem(PANDA_BLOCK_ID);
        PARROT_BLOCK = registerPlushieBlockAndItem(PARROT_BLOCK_ID);
        RED_FOX_BLOCK = registerPlushieBlockAndItem(RED_FOX_BLOCK_ID);
        WHITE_FOX_BLOCK = registerPlushieBlockAndItem(WHITE_FOX_BLOCK_ID);
        WARDEN_BLOCK = registerPlushieBlockAndItem(WARDEN_BLOCK_ID);
        SHEEP_BLOCK = registerPlushieBlockAndItem(SHEEP_BLOCK_ID);
        TURTLE_BLOCK = registerPlushieBlockAndItem(TURTLE_BLOCK_ID);
        ALLAY_BLOCK = registerPlushieBlockAndItem(ALLAY_BLOCK_ID);
        TADPOLE_BLOCK = registerPlushieBlockAndItem(TADPOLE_BLOCK_ID);
        PIG_BLOCK = registerPlushieBlockAndItem(PIG_BLOCK_ID);
        VEX_BLOCK = registerPlushieBlockAndItem(VEX_BLOCK_ID);
        BROWN_RABBIT_BLOCK = registerPlushieBlockAndItem(BROWN_RABBIT_BLOCK_ID);
        WHITE_RABBIT_BLOCK = registerPlushieBlockAndItem(WHITE_RABBIT_BLOCK_ID);
        BLACK_RABBIT_BLOCK = registerPlushieBlockAndItem(BLACK_RABBIT_BLOCK_ID);
        WHITE_SPLOTCHED_RABBIT_BLOCK = registerPlushieBlockAndItem(WHITE_SPLOTCHED_RABBIT_BLOCK_ID);
        YELLOW_RABBIT_BLOCK = registerPlushieBlockAndItem(YELLOW_RABBIT_BLOCK_ID);
        SALT_RABBIT_BLOCK = registerPlushieBlockAndItem(SALT_RABBIT_BLOCK_ID);
        KILLER_RABBIT_BLOCK = registerPlushieBlockAndItem(KILLER_RABBIT_BLOCK_ID);
        TOAST_RABBIT_BLOCK = registerPlushieBlockAndItem(TOAST_RABBIT_BLOCK_ID);
        STRIDER_BLOCK = registerPlushieBlockAndItem(STRIDER_BLOCK_ID);
        ENDERMITE_BLOCK = registerPlushieBlockAndItem(ENDERMITE_BLOCK_ID);
        CHICKEN_BLOCK = registerPlushieBlockAndItem(CHICKEN_BLOCK_ID);
        EVOKER_BLOCK = registerPlushieBlockAndItem(EVOKER_BLOCK_ID, Rarity.UNCOMMON);
        VINDICATOR_BLOCK = registerPlushieBlockAndItem(VINDICATOR_BLOCK_ID);
        ZOMBIE_BLOCK = registerPlushieBlockAndItem(ZOMBIE_BLOCK_ID);
        WOLF_BLOCK = registerPlushieBlockAndItem(WOLF_BLOCK_ID);
        SQUID_BLOCK = registerPlushieBlockAndItem(SQUID_BLOCK_ID);
        GLOW_SQUID_BLOCK = registerPlushieBlockAndItem(GLOW_SQUID_BLOCK_ID);
        PILLAGER_BLOCK = registerPlushieBlockAndItem(PILLAGER_BLOCK_ID);
        ILLUSIONER_BLOCK = registerPlushieBlockAndItem(ILLUSIONER_BLOCK_ID);
        CAMEL_BLOCK = registerPlushieBlockAndItem(CAMEL_BLOCK_ID);
        GUARDIAN_BLOCK = registerPlushieBlockAndItem(GUARDIAN_BLOCK_ID);
        ELDER_GUARDIAN_BLOCK = registerPlushieBlockAndItem(ELDER_GUARDIAN_BLOCK_ID);
        SNIFFER_BLOCK = registerPlushieBlockAndItem(SNIFFER_BLOCK_ID, Rarity.UNCOMMON);
        POLAR_BEAR_BLOCK = registerPlushieBlockAndItem(POLAR_BEAR_BLOCK_ID);
        WITCH_BLOCK = registerPlushieBlockAndItem(WITCH_BLOCK_ID);
        RAVAGER_BLOCK = registerPlushieBlockAndItem(RAVAGER_BLOCK_ID);
        HORSE_BLOCK = registerPlushieBlockAndItem(HORSE_BLOCK_ID);
        SPIDER_BLOCK = registerPlushieBlockAndItem(SPIDER_BLOCK_ID);
        CREEPER_BLOCK = registerPlushieBlockAndItem(CREEPER_BLOCK_ID);
        HUSK_BLOCK = registerPlushieBlockAndItem(HUSK_BLOCK_ID);
        WARM_FROG_BLOCK = registerPlushieBlockAndItem(WARM_FROG_BLOCK_ID);
        COLD_FROG_BLOCK = registerPlushieBlockAndItem(COLD_FROG_BLOCK_ID);
        PUFFERFISH_BLOCK = registerPlushieBlockAndItem(PUFFERFISH_BLOCK_ID);
        HOGLIN_BLOCK = registerPlushieBlockAndItem(HOGLIN_BLOCK_ID);
        OCELOT_BLOCK = registerPlushieBlockAndItem(OCELOT_BLOCK_ID);
        BAT_BLOCK = registerPlushieBlockAndItem(BAT_BLOCK_ID);
        SALMON_BLOCK = registerPlushieBlockAndItem(SALMON_BLOCK_ID);
        ZOGLIN_BLOCK = registerPlushieBlockAndItem(ZOGLIN_BLOCK_ID);
        COD_BLOCK = registerPlushieBlockAndItem(COD_BLOCK_ID);
        PIGLIN_BLOCK = registerPlushieBlockAndItem(PIGLIN_BLOCK_ID, Rarity.UNCOMMON);
        BRUTE_BLOCK = registerPlushieBlockAndItem(BRUTE_BLOCK_ID, Rarity.UNCOMMON);
        ZOMPIGLIN_BLOCK = registerPlushieBlockAndItem(ZOMPIGLIN_BLOCK_ID, Rarity.UNCOMMON);
        VILLAGER_BLOCK = registerPlushieBlockAndItem(VILLAGER_BLOCK_ID);
        WANDERING_TRADER_BLOCK = registerPlushieBlockAndItem(WANDERING_TRADER_BLOCK_ID);
        DROWNED_BLOCK = registerPlushieBlockAndItem(DROWNED_BLOCK_ID);
        SHULKER_BLOCK = registerPlushieBlockAndItem(SHULKER_BLOCK_ID);
        ZOMBIE_VILLAGER_BLOCK = registerPlushieBlockAndItem(ZOMBIE_VILLAGER_BLOCK_ID);
        GOLEM_BLOCK = registerPlushieBlockAndItem(GOLEM_BLOCK_ID);
        SKELETON_BLOCK = registerPlushieBlockAndItem(SKELETON_BLOCK_ID, Rarity.UNCOMMON);
        WITHER_SKELETON_BLOCK = registerPlushieBlockAndItem(WITHER_SKELETON_BLOCK_ID, Rarity.UNCOMMON);
        CAVE_SPIDER_BLOCK = registerPlushieBlockAndItem(CAVE_SPIDER_BLOCK_ID);
        SKELETON_HORSE_BLOCK = registerPlushieBlockAndItem(SKELETON_HORSE_BLOCK_ID);
        STRAY_BLOCK = registerPlushieBlockAndItem(STRAY_BLOCK_ID, Rarity.UNCOMMON);
        SILVERFISH_BLOCK = registerPlushieBlockAndItem(SILVERFISH_BLOCK_ID);
        BLAZE_BLOCK = registerPlushieBlockAndItem(BLAZE_BLOCK_ID);
        GHAST_BLOCK = registerPlushieBlockAndItem(GHAST_BLOCK_ID);
        WITHER_BLOCK = registerPlushieBlockAndItem(WITHER_BLOCK_ID, Rarity.EPIC);
        PHANTOM_BLOCK = registerPlushieBlockAndItem(PHANTOM_BLOCK_ID);
        SMALL_TROP_BLOCK = registerPlushieBlockAndItem(SMALL_TROP_BLOCK_ID);
        LARGE_TROP_BLOCK = registerPlushieBlockAndItem(LARGE_TROP_BLOCK_ID);
        ARMADILLO_BLOCK = registerPlushieBlockAndItem(ARMADILLO_BLOCK_ID);
        BREEZE_BLOCK = registerPlushieBlockAndItem(BREEZE_BLOCK_ID, Rarity.UNCOMMON);
        ZOMBIE_HORSE_BLOCK = registerPlushieBlockAndItem(ZOMBIE_HORSE_BLOCK_ID);
        BOGGED_BLOCK = registerPlushieBlockAndItem(BOGGED_BLOCK_ID, Rarity.UNCOMMON);
        MULE_BLOCK = registerPlushieBlockAndItem(MULE_BLOCK_ID);
        DONKEY_BLOCK = registerPlushieBlockAndItem(DONKEY_BLOCK_ID);

        PolymerItemGroupUtils.registerPolymerItemGroup(Identifier.of(MOD_ID, "item_group"), ITEM_GROUP);
    }

    public static Block registerPlushieBlockAndItem(Identifier id, Rarity rarity) {

        RegistryKey<Block> blockKey = RegistryKey.of(RegistryKeys.BLOCK, id);
        RegistryKey<Item> itemKey = RegistryKey.of(RegistryKeys.ITEM, id);
        Block block = Registry.register(Registries.BLOCK, id, new PlushieBlock(AbstractBlock.Settings.copy(net.minecraft.block.Blocks.WHITE_WOOL).registryKey(blockKey)));
        Item item = Registry.register(Registries.ITEM, id, new PlushieItem(block, new Item.Settings().registryKey(itemKey).useBlockPrefixedTranslationKey().maxCount(1).attributeModifiers(PlushieItem.createAttributeModifiers()).equipmentSlot((entity, stack) -> EquipmentSlot.HEAD).rarity(rarity)));
        BLOCKS.add(block);
        ITEMS.add(item);
        return block;
    }

    public static Block registerPlushieBlockAndItem(Identifier id) {
        return registerPlushieBlockAndItem(id, Rarity.COMMON);
    }
}
